# This is a basic workflow to help you get started with Actions

name: CI

 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

 

jobs:
  scheduled_run:
    name: scheduled_run
    runs-on: ubuntu-latest

 

    env:
      account: ${{ secrets.DBT_SNOWSQL_ACCOUNT }}
      database: ${{ secrets.DBT_SNOWSQL_DATABASE }}
      user: ${{ secrets.DBT_SNOWSQL_USER }}
      password: ${{ secrets.DBT_SNOWSQL_PWD }}
      role: ${{ secrets.DBT_SNOWSQL_ROLE }}
      schema: ${{ secrets.DBT_SNOWSQL_SCHEMA }}
      warehouse: ${{ secrets.DBT_SNOWSQL_WAREHOUSE }}

 

    steps:
      - uses: actions/checkout@v3

 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

 

      - name: Installing Python
        run: |
          python -m pip install --upgrade pip
          python -m pip install dbt-core dbt-snowflake
